import { PanelsTopLeft, Eraser, FolderOpen, Hand, MousePointer2, Palette, Plus, Redo2, Settings2, Trash2, Undo2 } from "lucide-react";

import { registerToolbarTools, type ToolDefinition } from "@/lib/canvas/tool-registry";
import type { CanvasToolMode } from "@/types/canvas";

const canvasModeOptions = [
    { id: "box-select", label: "区域选择", icon: <MousePointer2 />, value: "box-select", hover: { description: "框选批量选择节点" } },
    { id: "move", label: "抓手工具", icon: <Hand />, value: "move", hover: { description: "拖动平移画布视图" } },
];

export const mainToolbarTools: ToolDefinition[] = [
    { id: "tool-workspace", toolbar: "main", category: "navigation", label: "工作区", icon: <PanelsTopLeft />, defaultVisible: true, defaultOrder: 65, hover: { description: "展开左侧工作区：节点、资产与任务" }, run: ctx => ctx.handlers.onOpenWorkspace?.() },
    {
        id: "tool-canvas-mode",
        toolbar: "main",
        category: "navigation",
        label: "抓手 / 框选",
        icon: <MousePointer2 />,
        defaultVisible: true,
        defaultOrder: 10,
        switchGroup: {
            value: (ctx) => ctx.canvasTool,
            options: canvasModeOptions,
            onChange: (ctx, value) => ctx.handlers.onToolChange(value as CanvasToolMode),
        },
        run: (ctx) => ctx.handlers.onToolChange(ctx.canvasTool === "move" ? "box-select" : "move"),
    },
    {
        id: "tool-undo",
        toolbar: "main",
        category: "history",
        label: "撤销",
        icon: <Undo2 />,
        defaultVisible: true,
        defaultOrder: 30,
        hover: { description: "撤销上一步操作", shortcuts: ["undo"] },
        disabled: (ctx) => !ctx.canUndo,
        run: (ctx) => ctx.handlers.onUndo(),
    },
    {
        id: "tool-redo",
        toolbar: "main",
        category: "history",
        label: "重做",
        icon: <Redo2 />,
        defaultVisible: true,
        defaultOrder: 40,
        hover: { description: "恢复被撤销的操作", shortcuts: ["redo"] },
        disabled: (ctx) => !ctx.canRedo,
        run: (ctx) => ctx.handlers.onRedo(),
    },
    {
        id: "tool-add",
        toolbar: "main",
        category: "create",
        label: "添加节点",
        icon: <Plus />,
        defaultVisible: true,
        defaultOrder: 50,
        hover: { description: "打开添加面板，创建各类节点" },
        expands: true,
        active: (ctx) => ctx.addPanelOpen,
        run: (ctx, event) => ctx.handlers.onToggleAddPanel(event!),
    },
    {
        id: "tool-assets",
        toolbar: "main",
        category: "resource",
        label: "素材库",
        icon: <FolderOpen />,
        defaultVisible: true,
        defaultOrder: 60,
        hover: { description: "打开素材库，选择与管理素材" },
        applicable: (ctx) => !ctx.isProjectLinked,
        run: (ctx) => ctx.handlers.onOpenMyAssets(),
    },
    {
        id: "tool-style",
        toolbar: "main",
        category: "appearance",
        label: "画布外观",
        icon: <Palette />,
        defaultVisible: true,
        defaultOrder: 70,
        hover: { description: "调整画布背景与显示偏好" },
        expands: true,
        active: (ctx) => ctx.appearancePanelOpen,
        run: (ctx, event) => ctx.handlers.onToggleAppearancePanel(event!),
    },
    {
        id: "tool-settings",
        toolbar: "main",
        category: "appearance",
        label: "工具栏设置",
        icon: <Settings2 />,
        defaultVisible: true,
        defaultOrder: 80,
        hover: { description: "选择显示哪些工具并调整顺序" },
        expands: true,
        active: (ctx) => ctx.settingsPanelOpen,
        run: (ctx) => ctx.handlers.onToggleSettingsPanel(),
    },
    {
        id: "tool-delete",
        toolbar: "main",
        category: "danger",
        label: (ctx) => ctx.selectedCount > 1 ? `删除 ${ctx.selectedCount} 个节点` : "删除选中节点",
        icon: <Trash2 />,
        defaultVisible: true,
        defaultOrder: 90,
        hover: { description: "删除当前选中的节点，可撤销", shortcuts: ["delete"] },
        danger: true,
        applicable: (ctx) => ctx.selectedCount > 0,
        run: (ctx) => ctx.handlers.onDeleteSelected(),
    },
    {
        id: "tool-clear",
        toolbar: "main",
        category: "danger",
        label: "清空画布",
        icon: <Eraser />,
        defaultVisible: true,
        defaultOrder: 100,
        hover: { description: "清空画布上的全部内容，清空前请确认" },
        danger: true,
        run: (ctx) => ctx.handlers.onClear(),
    },
];

registerToolbarTools(mainToolbarTools);
