import { PanelsTopLeft, Eraser, FolderOpen, Hand, MousePointer2, Palette, Plus, Redo2, Settings2, Trash2, Undo2 } from "lucide-react";

import { registerToolbarTools, type ToolDefinition } from "@/lib/canvas/tool-registry";
import type { CanvasToolMode } from "@/types/canvas";

const canvasModeOptions = [
    { id: "box-select", label: "区域选择", icon: <MousePointer2 />, value: "box-select", hover: { tagline: "框选批量选择节点", description: "在画布空白处拖出选框即可批量选中节点；只做选择，不会移动或修改任何节点。" } },
    { id: "move", label: "抓手工具", icon: <Hand />, value: "move", hover: { tagline: "拖动平移画布视图", description: "按住拖动即可平移视图，不会误选或移动画布中的节点。" } },
];

export const mainToolbarTools: ToolDefinition[] = [
    { id: "tool-workspace", toolbar: "main", category: "navigation", label: "工作区", icon: <PanelsTopLeft />, defaultVisible: true, defaultOrder: 65, hover: { tagline: "打开左侧工作区", description: "展开左侧面板，集中管理本项目的节点、资产与任务。" }, run: ctx => ctx.handlers.onOpenWorkspace?.() },
    {
        id: "tool-canvas-mode",
        toolbar: "main",
        category: "navigation",
        label: "抓手 / 框选",
        icon: <MousePointer2 />,
        defaultVisible: true,
        defaultOrder: 10,
        switchGroup: {
            value: (ctx) => ctx.canvasTool,
            options: canvasModeOptions,
            onChange: (ctx, value) => ctx.handlers.onToolChange(value as CanvasToolMode),
        },
        run: (ctx) => ctx.handlers.onToolChange(ctx.canvasTool === "move" ? "box-select" : "move"),
    },
    {
        id: "tool-undo",
        toolbar: "main",
        category: "history",
        label: "撤销",
        icon: <Undo2 />,
        defaultVisible: true,
        defaultOrder: 30,
        hover: { tagline: "撤销上一步操作", description: "回退最近一步编辑，节点、连线与画布设置都能恢复。", shortcuts: ["undo"] },
        disabled: (ctx) => !ctx.canUndo,
        run: (ctx) => ctx.handlers.onUndo(),
    },
    {
        id: "tool-redo",
        toolbar: "main",
        category: "history",
        label: "重做",
        icon: <Redo2 />,
        defaultVisible: true,
        defaultOrder: 40,
        hover: { tagline: "恢复被撤销的操作", description: "重新应用刚撤销的编辑，误撤销时从这里找回。", shortcuts: ["redo"] },
        disabled: (ctx) => !ctx.canRedo,
        run: (ctx) => ctx.handlers.onRedo(),
    },
    {
        id: "tool-add",
        toolbar: "main",
        category: "create",
        label: "添加节点",
        icon: <Plus />,
        defaultVisible: true,
        defaultOrder: 50,
        hover: { tagline: "打开添加面板", description: "展开创建菜单，挑选要添加的内容类型。" },
        expands: true,
        active: (ctx) => ctx.addPanelOpen,
        run: (ctx, event) => ctx.handlers.onToggleAddPanel(event!),
    },
    {
        id: "tool-assets",
        toolbar: "main",
        category: "resource",
        label: "素材库",
        icon: <FolderOpen />,
        defaultVisible: true,
        defaultOrder: 60,
        hover: { tagline: "浏览与管理素材", description: "打开素材空间，选取已有素材使用，或统一整理与清理。" },
        applicable: (ctx) => !ctx.isProjectLinked,
        run: (ctx) => ctx.handlers.onOpenMyAssets(),
    },
    {
        id: "tool-style",
        toolbar: "main",
        category: "appearance",
        label: "画布外观",
        icon: <Palette />,
        defaultVisible: true,
        defaultOrder: 70,
        hover: { tagline: "调整画布显示", description: "调整画布背景与显示偏好，随时可以改回。" },
        expands: true,
        active: (ctx) => ctx.appearancePanelOpen,
        run: (ctx, event) => ctx.handlers.onToggleAppearancePanel(event!),
    },
    {
        id: "tool-settings",
        toolbar: "main",
        category: "appearance",
        label: "工具栏设置",
        icon: <Settings2 />,
        defaultVisible: true,
        defaultOrder: 80,
        hover: { tagline: "管理工具栏按钮", description: "选择工具栏显示哪些按钮、调整排列顺序；不影响画布内容。" },
        expands: true,
        active: (ctx) => ctx.settingsPanelOpen,
        run: (ctx) => ctx.handlers.onToggleSettingsPanel(),
    },
    {
        id: "tool-delete",
        toolbar: "main",
        category: "danger",
        label: (ctx) => ctx.selectedCount > 1 ? `删除 ${ctx.selectedCount} 个节点` : "删除选中节点",
        icon: <Trash2 />,
        defaultVisible: true,
        defaultOrder: 90,
        hover: { tagline: "移除所选内容", description: "移除选中的节点及其连线，可在会话内撤销。", shortcuts: ["delete"] },
        danger: true,
        applicable: (ctx) => ctx.selectedCount > 0,
        run: (ctx) => ctx.handlers.onDeleteSelected(),
    },
    {
        id: "tool-clear",
        toolbar: "main",
        category: "danger",
        label: "清空画布",
        icon: <Eraser />,
        defaultVisible: true,
        defaultOrder: 100,
        hover: { tagline: "移除全部内容", description: "清空画布上的全部内容，清空前请确认。" },
        danger: true,
        run: (ctx) => ctx.handlers.onClear(),
    },
];

registerToolbarTools(mainToolbarTools);
